- deployments/roundtable/kustomization.yaml
Ah, yaml.  It's like programming, but worse.
> [DM-23217] Add logging into kustomization.yaml

- deployments/logging/values.yaml
This is the latest version, let's give it a shot.
> [DM-23217] Elasticsearch to 1.3.0

- docs/ops/vault/index.rst
Fix a couple of issues that came up during the Vault migration and cutover.
> [DM-23270] Fix Vault documentation issues

- deployments/cert-manager/templates/cluster-issuer.yaml
- docs/ops/argo-cd/index.rst
- Add new documentation page to index
- Revert `apiVersion` change for the `ClusterIssuer`
> [DM-25624] Fix some deployment issues with new cert-manager

- deployments/security/resources/cert-manager.yaml
Also include the ValidatingWebhookConfiguration.
> Ignore another variation of cert-manager difference

- deployments/nginx-ingress/requirements.yaml
- deployments/nginx-ingress/values.yaml
This is a fairly major upgrade but I can't find any notes about breaking changes, and we've been running newer versions in other environments.
> [DM-25624] Upgrade nginx-ingress to 1.40.1

- deployments/templatebot/patches/templatebot-configmap.yaml
This temporary change lets us get real-time feedback for https://github.com/lsst/templates/pull/88
> DM-25657: Switch to tickets/DM-25657 of templates

- deployments/templatebot/kustomization.yaml
This will help us test new user feedback with document templates.
> DM-25659: Use `DM-25659` branch of templatebot-aide

- deployments/templatebot/kustomization.yaml
To assist with developing user feedback when creating from templates.
> DM-25659: Switch to DM-25659 version of templatebot

- docs/ops/nginx-ingress/index.rst
- docs/ops/prometheus/index.rst
Document the update procedure for the prometheus and nginx-ingress
apps.  Document the handling of the public IP for the nginx-ingress.
> [DM-25624] Add upgrade docs for prometheus and nginx-ingress

- deployments/safirdemo/kustomization.yaml
This deploys a version that logs all incoming headers, to allow
for debugging an nginx-ingress problem with Flask applications.
> [DM-25624] Deploy safirdemo from a ticket branch

- deployments/safirdemo/kustomization.yaml
> [DM-25624] Restore previous version of safirdemo

- deployments/templatebot/patches/templatebot-configmap.yaml
See https://github.com/lsst/templates/pull/88
> DM-25657: Update template repo to master

- deployments/lsst-the-docs/kustomization.yaml
This is the finalized deployment of this ticket branch (merge after testing in https://github.com/lsst-sqre/roundtable/pull/91)
> DM-25740: Deploy version LTD Keeper 1.19.0

- deployments/app-land/resources/neophile.yaml
- deployments/neophile/Chart.yaml
- deployments/neophile/README.md
- deployments/neophile/requirements.yaml
- deployments/neophile/values.yaml
This will run periodically to look at our GitHub repositories for
needed dependency updates and create pull requests.
> [DM-25844] Add neophile application

- deployments/neophile/requirements.yaml
Pick up a fix to indentation of metadata labels for the CronJob
spec.
> [DM-25844] Bump version of neophile chart

- deployments/neophile/values.yaml
The owner and repo settings for neophile were reversed.
> [DM-25844] Fix neophile repository configuration

- deployments/vault/values.yaml
This appears to be required with the new Helm chart.
> Add service registration to Vault config

- deployments/vault/values.yaml
Upgrade to the latest version.  None of the changes appear to be
relevant to us, but there are security fixes.
> Upgrade Vault to 1.5.3

- docs/ops/logging/index.rst
Explain how to upgrade the logging application, including some
gotchas about restart timing.  Document how to recreate an index
if the persistent storage is lost.
> [DM-26508] Add upgrading documentation for logging

- deployments/logging/templates/networkpolicy.yaml
Too much indentation for most of the policy.
> [DM-26602] Fix syntax of logging NetworkPolicy

- deployments/logging/templates/logging-security-config.yaml
This is needed for Kibana and fluentd.
> [DM-26602] Add Elasticsearch internal auth domain

- deployments/logging/templates/networkpolicy.yaml
- deployments/logging/values.yaml
- Set a base path for Kibana
- Try to fix the NetworkPolicy to allow ingress traffic
> [DM-26602] Further Kibana fixes

- deployments/logging/values.yaml
We're still hitting errors about requests being too long.  See if
this will fix that problem.
> [DM-26602] Bump sizing of Elasticsearch nodes

- deployments/logging/values.yaml
The configuration was missing a few parameters.
> [DM-26602] Fix Kibana OpenID configuration

- deployments/lsst-the-docs/kustomization.yaml
> Use tickets/DM-27608-3 branch of LTD Keeper

- deployments/lsst-the-docs/kustomization.yaml
- deployments/lsst-the-docs/patches/dasher-deployment.yaml
- deployments/lsst-the-docs/patches/keeper-deployment.yaml
Add extra capacity to catch up with the work queue.
> Scale up LTD Keeper and Dasher deployments

- deployments/lsst-the-docs/kustomization.yaml
Debug with additional/better logging.
> Switch LTD Keeper to DM-27702 builds

- deployments/lsst-the-docs/kustomization.yaml
This will preview the new bulk metadata endpoint.
> Deploy DM-27702 version of LTD Dasher

- deployments/lsst-the-docs/patches/dasher-deployment.yaml
> DM-27805: Reduce LTD Dasher replication to 1

- deployments/events/kustomization.yaml
Cluster can't be recovered so I'm attempting to fully restart it.
> DM-27995: Drop events Kafka cluster

- deployments/argo-cd/resources/argocd-grafana-dashboard-cm.yaml
Sync to the latest upstream version since I'm upgrading Grafana
anyway.
> [DM-27977] Update Argo CD dashboard

- deployments/neophile/Chart.yaml
Pick up a fix for how the required function was being used.
> [DM-29329] Bump neophile chart version

- deployments/neophile/Chart.yaml
Pick up another fix for generating the ConfigMap.
> [DM-29329] Bump version of neophile chart

- deployments/neophile/Chart.yaml
Pick up the new release and the fix for home directory writability.
> [DM-29329] Bump neophile chart

- deployments/vault/values.yaml
The changes do not look like they will affect our installation.
> Bump version of Vault to 1.9.0

- deployments/events/kustomization.yaml
This fixes a bug in the kustomization for strimzi-registry-operator in 0.4.0
> DM-33317: Deploy strimzi-registry-operator 0.4.1

- renovate.json
> Fix syntax of Renovate configuration

- deployments/neophile/Chart.yaml
Pick up fixes for setting automerge.
> [DM-33830] Upgrade neophile

- deployments/sherlock-frontend/resources/secret.yaml
Forgot secret name and apparently it doesn't merge it.
> [DM-33787] Add secret name

- deployments/app-land/resources/sherlock-frontend.yaml
> [DM-33787] Add namespace for sherlock

- deployments/sherlock-frontend/kustomization.yaml
Apparently this was what I was missing...
> [DM-33787] Bump to latest release

- deployments/sherlock-frontend/kustomization.yaml
This allows for /tmp to be writable.
> [DM-34074] Sherlock-FE to 0.0.13

- deployments/argo-cd/patches/argocd-cm.yaml
- deployments/monitoring/Chart.yaml
- deployments/monitoring/values.yaml
(also ignore aggregated roles so monitoring shows in sync)
> DM-35234: Add telegraf-ds to get host statistics

- deployments/rubintv/kustomization.yaml
- deployments/templatebot/kustomization.yaml
- lsst-templatebot-aide 0.5.0 with support for SPIE and ADASS technote templates
- rubintv 0.3.0
> DM-36698: Updates for rubintv and templatebot-aide

- deployments/1password-connect/values.yaml
Was missing one layer of dictionary.
> DM-37221: Fix nesting of 1password-connect configuration

- deployments/app-land/resources/onepassword-connect-ns.yaml
- deployments/app-land/resources/onepassword-connect.yaml
Forgot the Argo CD application and namespace.
> DM-37721: Rename more 1password-connect things

- deployments/onepassword-connect/templates/ingress.yaml
We need to strip off our path prefix.
> DM-37721: Add rewriting for onepassword-connect

- deployments/events/kustomization.yaml
- deployments/lsst-the-docs/kustomization.yaml
- deployments/ltdevents/kustomization.yaml
- deployments/ook/kustomization.yaml
- deployments/sqrbot-jr/kustomization.yaml
- deployments/sqrbot-jsick/kustomization.yaml
- deployments/templatebot-jsick/kustomization.yaml
- deployments/templatebot/kustomization.yaml
patches should now be patchesStrategicMerge.
> DM-39253: Update for new Kustomize syntax

- deployments/sqrbot/resources/deployment.yaml
Failure to launch sqrbot; will investigate.
> Revert sqrbot back to previous version on dockerhub

- deployments/sqrbot/resources/deployment.yaml
The hubot starts and logs in, but seems to have an error reading
messages.
> Revert sqrbot again
