lsst-sqre/roundtable

deployments/nginx-ingress/requirements.yaml
The current nginx TLS configuration allows TLS 1.0 and 1.1, as well
as some weaker ciphers, and therefore only achieves a grade of B
in SSL Labs.  The new version of the Helm chart updates the TLS
configuration to only allow TLS 1.2 and 1.3 and refreshes the
cipher list.
=> [DM-23286] Upgrade nginx-ingress chart to 1.29.7

deployments/nginx-ingress/values.yaml
The nginx-ingress Helm chart has reintroduced an issue with
clusterIP on upgrades that was previously fixed.  The clusterIP
has to be hard-coded to successfully upgrade unless the prior
version was installed with omitClusterIP, which it wasn't for our
configuration.
Hard-code the existing clusterIPs for now until upstream finds a
better fix.
=> [DM-23286] Work around nginx clusterIP bug

deployments/logging/values.yaml
This one unlike the other was enabled by default.  Let's turn
that off.
=> [DM-23217] Disable elasticsearch client ingress

deployments/argo-cd/patches/argocd-rbac-cm.yaml
Rather than using the URL form of the GitHub team name, use the
display name.  This appears to be what the built-in Dex SSO in
Argo CD expects based on experience with the EFD cluster.
=> For Argo CD RBAC, use correct GitHub team

deployments/vault/values.yaml
Enable vault.lsst.codes as an additional hostname for the Vault
ingress.  This will also trigger acquiring a Let's Encrypt
certificate.  This should not interfere with the existing Vault
server, since it's using a *.lsst.codes wildcard certificate.
The DNS entry for vault.lsst.codes must be changed to point to
Roundtable before this is merged so that the Let's Encrypt
certificate validation will succeed.
=> [DM-23270] Add vault.lsst.codes to Vault ingress

deployments/nginx-ingress/values.yaml
The Argo CD health check for an ingress waits for the
status.loadBalancer.ingress list to be updated, but the nginx
ingress controller does not do that by default.
Set the flag in its configuration that tells it to publish the
service information to the ingress, hopefully fixing this issue.
See the Argo CD FAQ at:
https://github.com/argoproj/argo-cd/blob/master/docs/faq.md
=> [DM-23532] Fix Argo CD health checks on ingress

deployments/app-land/kustomization.yaml, deployments/app-land/resources/checkerboard.yaml, deployments/app-land/resources/roundtable-ingress.yaml, deployments/argo-cd/patches/argocd-cm.yaml, deployments/checkerboard/README.md, deployments/checkerboard/kustomization.yaml, deployments/checkerboard/resources/secret.yaml, deployments/ghslacker/README.md, deployments/ghslacker/resources/secret.yaml, docs/app-guide/ingress.rst
Also adds missing Git repository monitoring for Argo CD and sorts that list.
=> [DM-23507] Rename ghslacker to checkerboard

deployments/app-land/resources/roundtable-ingress.yaml, deployments/app-land/resources/roundtable-issuer.yaml, deployments/argo-cd/resources/argocd-grpc-ingress.yaml, deployments/argo-cd/resources/argocd-grpc-issuer.yaml, deployments/argo-cd/resources/argocd-ui-ingress.yaml, deployments/argo-cd/resources/argocd-ui-issuer.yaml, deployments/cert-manager-crd/README.md, deployments/cert-manager-crd/certmanager-crd-0.13.1.yaml, deployments/cert-manager-crd/kustomization.yaml, deployments/cert-manager/requirements.yaml, deployments/lsst-the-docs/resources/keeper-ingress.yaml, deployments/lsst-the-docs/resources/keeper-issuer.yaml, deployments/prometheus/templates/grafana-ingress.yaml, deployments/prometheus/templates/grafana-issuer.yaml, deployments/security/resources/cert-manager.yaml, deployments/vault/templates/vault-issuer.yaml, deployments/vault/values.yaml, docs/app-guide/ingress.rst, docs/ops/cert-manager/index.rst
Import new CRDs from the upstream Git repository and update the
cert-manager-crd app to deploy them.  Add some operational docs for
why this is a separate app and how it is updated.
Update all issuers to use the new API group and the new syntax for
specifying the solver.
Update all annotations to use the new annotation label for specifying
the issuer.
Remove the Argo CD ignoreDifferences configuration to see if this
problem is fixed with the latest cert-manager.
Remove the disable-validation annotation for the cert-manager 
namespace since that upstream documentation page no longer exists
and upstream no longer appears to recommend this change.
=> [DM-23547] Upgrade to cert-manager 0.13.1

deployments/events/kustomization.yaml, deployments/events/resources/ltdevents-topics.yaml, deployments/events/resources/ltdevents-user.yaml
These updates are for the future deployment of LTD Events (https://github.com/lsst-sqre/ltd-events):
- `ltd.events topic` is what LTD Events produces to (different types of events are multiplexed). It has a long retention so that we can effectively keep a log of documentation update activity.
- `ltdevents` Kafka user that produces messages to the ltd.events topic. At the moment this user doesn't consume any topics, but it's conceivable that it'll consume GitHub topics in the future.
=> DM-23899: Add Kafka User and Topic for LTD Events

deployments/app-land/kustomization.yaml, deployments/app-land/resources/ltdevents.yaml, deployments/app-land/resources/roundtable-ingress.yaml, deployments/argo-cd/patches/argocd-cm.yaml, deployments/ltdevents/README.md, deployments/ltdevents/kustomization.yaml, deployments/ltdevents/patches/configmap.yaml, deployments/ltdevents/patches/deployment.yaml
This PR adds the ltdevents application (available at a `/ltdevents/` external endpoint). The application is tracking the `tickets/DM-23731` branch of https://github.com/lsst-sqre/ltd-events (https://github.com/lsst-sqre/ltd-events/pull/1).
=> DM-23731: Initial deployment of ltd events application

deployments/lsst-the-docs/kustomization.yaml, deployments/lsst-the-docs/patches/keeper-deployment.yaml, deployments/ltdevents/patches/configmap.yaml
This version of LTD Keeper posts `ltd.updated` webhook payloads to the `http://ltdevents.events:8080/webhook` internal endpoint of the `ltdevents` app.
=> DM-23899: Deploy LTD Keeper with LTD Events integration

deployments/app-land/resources/roundtable-ingress.yaml, deployments/argo-cd/resources/argocd-grpc-ingress.yaml, deployments/argo-cd/resources/argocd-ui-ingress.yaml, deployments/logging/requirements.yaml, deployments/lsst-the-docs/resources/keeper-ingress.yaml, deployments/prometheus/templates/grafana-ingress.yaml, docs/app-guide/ingress.rst, docs/ops/argo-cd/argocd-github-sso.rst
Kubernetes 1.22 will drop support for defining Ingress resources
with the extensions/v1beta1 apiVersion.  Switch all of them to
networking.k8s.io/v1beta1, supported since 1.14.
=> [DM-23546] Update apiVersion for Ingress resources

deployments/logging/values.yaml
The Helm chart sets these to an appropriate value.  Don't pin to a
version or we end up stuck on an older version when upgrading.
=> [DM-23546] Remove pinning of opendistro-es images

deployments/logging/values.yaml
The new Helm chart reduces the replicas to 1 for all the components,
which is causing the master to decline to start.  Increase the
replica count to 3 for the master and data servers and 2 for the
client to match the previous configuration.
=> [DM-23546] Restore Elasticsearch replica count

docs/ops/prometheus/index.rst
Fix a cut and paste error that had it pointing to the cert-manager
Helm chart instead.
=> Fix link to the prometheus-operator Helm chart

deployments/logging/README.md, deployments/nginx-ingress/README.md, docs/app-guide/index.rst, docs/app-guide/viewing-logs.rst, docs/conf.py, docs/ops/index.rst, docs/ops/logging/index.rst
This PR is to add some documentation coverage for the logging service in Roundtable:
- User doc: https://roundtable.lsst.io/v/DM-23918/app-guide/viewing-logs.html
- Ops doc: https://roundtable.lsst.io/v/DM-23918/ops/logging/index.html
- README for the deployment
=> DM-23918: Add user and ops docs for the logging service

deployments/prometheus/values.yaml
See if this causes it to install the default Grafana dashboards,
as implied by https://github.com/helm/charts/issues/16943.
=> [DM-23546] Set the Kubernetes version for Prometheus

deployments/safirdemo/kustomization.yaml, docs/ops/events/cluster-config-overview.rst
The Roundtable configuration was pointing at a branch that no
longer exists.
=> [DM-24965] Update safirdemo to 0.1.1

deployments/lsst-the-docs/kustomization.yaml
This updates the LTD Dasher deployment to omit Travis CI links from LSST the Docs dashboards.
=> DM-25234: Deploy LTD Dasher 0.1.6

deployments/templatebot/kustomization.yaml, deployments/templatebot/patches/templatebot-aide-deployment.yaml
This release works with GitHub Actions-based technote templates.
See https://github.com/lsst/templates/pull/80
=> DM-25233: Update templatebot-aide to 0.2.0

deployments/templatebot/kustomization.yaml, deployments/templatebot/patches/templatebot-configmap.yaml
- Set templatebot to use the tickets/DM-25331 branch of lsst/templates to test the new test_report and latex_lsstdoc templates.
- Use tickets-DM-25331 version of templatebot-aide to get support for the test_report and latex_lsstdoc templates.
=> DM-25331: Test DM-25331 version of templatebot-aide

deployments/cert-manager/Chart.yaml, deployments/checkerboard/kustomization.yaml, deployments/logging/Chart.yaml, deployments/nginx-ingress/Chart.yaml, deployments/prometheus/Chart.yaml, deployments/strimzi/Chart.yaml, deployments/vault-secrets-operator/Chart.yaml, deployments/vault/Chart.yaml, deployments/vault/requirements.yaml
- Add the repository for the vault Helm chart
- Try a different format for the Kustomize resource URL to see if it fixes a renovatebot issue
- Add `apiVersion` and `version` to all stub Helm charts, since renovatebot won't analyze them otherwise
=> [DM-25183] Help automated upgrade detection

deployments/checkerboard/kustomization.yaml
This reverts commit b01a1bf2a54a8d57a4692b89949c4226b191c4b6.
Renovate cannot cope with Kustomize GitHub URLs in either format.
=> Revert "[DM-25183] Try different kustomize resource URL"

deployments/templatebot/kustomization.yaml, deployments/templatebot/patches/templatebot-configmap.yaml
- Updates templatebot configuration to point at lsst/templates's master branch since lsst/templates#86 is merged.
- Deploys lsst-templatbot-aide 0.3.0, which is the released version of the ticket branch that was previously deployed.
=> DM-25331: Complete deployment of templatebot-aide for test_report and latex_lsstdoc templates

deployments/templatebot/kustomization.yaml
These new versions incorporate aiokafka 0.6.0, which should prevent consumers from unexpectedly failing due to unhandled `UnknownMemberId` errors.
=> DM-25427: Update to templatebot 0.1.1, -aide 0.3.1

deployments/templatebot/patches/templatebot-deployment.yaml
This was preventing the base manifest from successfully setting its own tag. It was probably originally done to override a tagging error in the 0.1.0 release.
=> DM-25427: Remove templatebot image/tag from patch

deployments/app-land/kustomization.yaml, deployments/app-land/resources/ook.yaml, deployments/argo-cd/patches/argocd-cm.yaml, deployments/events/kustomization.yaml, deployments/events/resources/ook-topics.yaml, deployments/events/resources/ook-user.yaml, deployments/ook/README.md, deployments/ook/kustomization.yaml, deployments/ook/patches/configmap.yaml, deployments/ook/patches/deployment.yaml, deployments/ook/resources/vaultsecret.yaml
This adds Ook (https://github.com/lsst-sqre/ook) to Roundtable:
- Adds the ook Argo CD Application to app-land
- Adds the deployment, which consists of two Deployments:
1. ook-queue (the front-end pods)
2. ook-ingest (the back-end pods)
- Adds the ook.ingest Kafka topic
- Adds the ook-ingest and ook-queue KafkaUsers.
=> DM-24958: Preliminary initial Ook deployment

deployments/ook/kustomization.yaml
This finalizes the DM-24958 deployment, which we've validated as successful.
=> DM-24958: Deploy ook 0.1.0

deployments/security/resources/cert-manager.yaml
The MutatingWebhookConfiguration resources for cert-manager add a
caBundle attribute dynamically.  Tell Argo CD to ignore that for
calculating differences.
=> Ignore differences in cert-manager webhooks

deployments/vault/values.yaml
Upgrade Vault to the latest release.  I reviewed the upgrading
guides at:
https://www.vaultproject.io/docs/upgrading/upgrade-to-1.4.0
and for the other version increases, and none of them seem relevant
to this deployment.
=> [DM-25624] Upgrade Vault to 1.4.1

deployments/logging/requirements.yaml, deployments/roundtable/resources/logging.yaml
Pin to the latest version so that we won't attempt to automatically
pick up newer versions and show as out-of-date on Argo CD and enable
automatic synchronization to match the other Roundtable
configurations.
=> [DM-25624] Pin the fluentd-elasticsearch version

docs/app-guide/index.rst, docs/app-guide/using-sealed-secrets.rst, docs/app-guide/using-vault-secrets.rst
https://dmtn-112.lsst.io leaves out details of how to use Vault and Vault Secrets Operator as an application developer. This documentation attempts to fill that gap.
First, it provides background concepts to help users understand the terminology.
Then it includes a how-to guide that describes how to carry out key tasks related to Vault and integrating Vault secrets into apps as either environment variables or mounted files.
See https://roundtable.lsst.io/v/DM-25459/app-guide/using-vault-secrets.html for a draft.
=> DM-25459: App developer documentation for Vault and Vault Secrets Operator

deployments/nginx-ingress/values.yaml
Per the documentation, GKE should support this feature.
=> [DM-25624] Force the external IP for nginx-ingress

deployments/argo-cd/kustomization.yaml
Upgrade Argo CD to the latest version.  This will require a newer
Argo CD client, but otherwise none of the upgrade notes indicate
problems for Roundtable that I can see.
=> [DM-25624] Upgrade Argo CD to 1.6.1

deployments/templatebot/kustomization.yaml
This releases templatebot 0.1.2 (https://github.com/lsst-sqre/templatebot/pull/11) and lsst-templatebot-aide 0.3.3 (https://github.com/lsst-sqre/lsst-templatebot-aide/pull/11)
=> DM-25659: Release templatebot 0.1.2, -aide 0.3.3

deployments/lsst-the-docs/kustomization.yaml
This enables testing of the new version under the realistic nginx-ingress conditions.
=> DM-25740: Switch to DM-25740 branch of ltd-keeper

deployments/lsst-the-docs/kustomization.yaml, deployments/lsst-the-docs/patches/keeper-deployment.yaml
This enables the new proxy header trust settings available in LTD Keeper version 1.19.0.
=> DM-25740: Configure LTD to use ProxyFix

deployments/argo-cd/kustomization.yaml
This works around the issue discussed in https://github.com/argoproj/argo-cd/issues/3814 due to changes in kustomize and go-getter. Essentially, with the `//` technique of downloading a single directory, other directories outside that tree
couldn't be resolved.
=> Use full URL for Argo CD manifest

deployments/app-land/kustomization.yaml, deployments/neophile/values.yaml
Add the Vault path to the secret and include the application in the
app-land configuration.
=> [DM-25844] Add missing configuration for neophile

deployments/neophile/values.yaml
Add the github_email configuration setting pointing to the noreply
mail for sqrbot, and add neophile to the set of repositories to
monitor.
=> [DM-25844] Add additional neophile configuration

deployments/neophile/requirements.yaml, deployments/neophile/values.yaml
Use the default schedule and the default image, now that 0.1.0 has
been formally released and everything seems to be working.
=> [DM-25844] Use defaults for neophile

deployments/argo-cd/resources/argocd-grafana-dashboard-cm.yaml, docs/ops/argo-cd/grafana-dashboard.rst, docs/ops/argo-cd/index.rst
I noticed this wasn't working after a Prometheus update. This should
hopefully fix it. Not tested, so some iteration may be required.
The Argo CD dashboard stopped displaying the counts of applications
in various states because the capitalization of the data source has
changed.  Update the dashboard to the latest upstream release, which
fixes that problem among others.
Add documentation for the Grafana dashboard.
=> Update Argo CD dashboard

deployments/vault/Chart.yaml, deployments/vault/requirements.yaml
Roundtable is unable to sync because the upstream Helm chart is now
apiVersion: v2.  See if the problem is that the wrapper chart is not
apiVersion: v2, so Argo CD is explicitly invoking helm2 on it.
=> Convert Vault wrapper chart to apiVersion: v2

deployments/neophile/values.yaml
In https://github.com/lsst-sqre/ltd-keeper/pull/53 we upgraded LTD Keeper to use resolved/pinned dependencies, so we can now use neophile to keep those dependencies up to date.
=> DM-26354: Add ltd-keeper to neophile

deployments/logging/values.yaml
Copy the settings from the lsp-deploy configuration but lower the
limits.  See if this addresses the issues with searching.
=> [DM-26508] Bump memory allocation for Kibana pods

deployments/logging/values.yaml
Telling Java to use 1GB but only requesting 1GB and limiting to 1GB
doesn't work for obvious reasons.  Request 2GB of memory and let
Java use 1GB of it.
=> [DM-26508] Further increase Kubernetes memory requests

deployments/logging/values.yaml
The configuration syntax apparently changed with the new version
to require a list of hosts including the port number.
=> [DM-26508] Fix elasticsearch host in fluentd configuration

docs/ops/vault/index.rst
Vault requires manual intervention for an upgrade, and some more
manual steps to work around an Argo CD bug.  Add documentation for
this process.
=> [DM-26549] Add Vault upgrade instructions

deployments/neophile/values.yaml
sqrbot also has write permissions on the lsst-sqre/ltd-conveyor repo.
=> DM-26527: Add ltd-conveyor to neophile config

deployments/argo-cd/kustomization.yaml, docs/ops/argo-cd/index.rst, docs/ops/argo-cd/upgrading.rst
Document how to upgrade Argo CD on Roundtable and bump the version
in the Kustomize external resource in preparation for that upgrade.
=> [DM-26507] Document Argo CD upgrade, bump version

docs/ops/argo-cd/upgrading.rst
Reflect the fact that Argo CD can indeed upgrade itself. Document configuration backups.
=> Update Argo CD upgrade documentation

deployments/cert-manager/templates/cluster-issuer.yaml
We've upgraded Roundtable to cert-manager v1, so update the
apiVersion of the ClusterIssuer resource to use the stable API.
=> Update cert-manager ClusterIssuer to stable API

deployments/app-land/kustomization.yaml, deployments/app-land/resources/gafaelfawr.yaml, deployments/gafaelfawr/Chart.yaml, deployments/gafaelfawr/requirements.yaml, deployments/gafaelfawr/values.yaml, deployments/roundtable/kustomization.yaml, docs/conf.py, docs/ops/argo-cd/upgrading.rst, docs/ops/gafaelfawr/index.rst, docs/ops/index.rst, docs/ops/roundtable/index.rst
This will take over the /login, /logout, and /auth routes, which
should be merged with the routes declared by the Roundtable ingress
and inherit the TLS settings from them.
Point at the current development branch since this will be tested as
an OpenID Connect provider for Open Distro for Elasticsearch.
=> [DM-25727] Deploy Gafaelfawr on Roundtable

deployments/gafaelfawr/values.yaml
The tokens endpoint requires exec:user.  Map it to the square team
in lsst-sqre as well.
=> [DM-25727] Add exec:user scope to Gafaelfawr

deployments/logging/templates/logging-accounts.yaml, deployments/logging/templates/logging-security-config.yaml, deployments/logging/templates/networkpolicy.yaml, deployments/logging/values.yaml
Use Gafaelfawr to authenticate Kibana from Open Distro for
Elasticsearch via proxy authentication.  This looks simpler than
using OpenID Connect on the Kubernetes configuration side.
Enable the ingress but limit access to nginx-ingress via a
network policy.
Explicitly configure the users and passwords for Kibana and
logstash using a secret rather than using the default values.
=> [DM-26602] Add security configuration and ingress for Kibana

deployments/logging/templates/logging-security-config.yaml
The regular Secret should be v1, not the apiVersion for a
VaultSecret.
=> [DM-26602] Fix apiVersion for logging secret

deployments/logging/values.yaml
It's way too aggressive at one minute.  The software was still
starting when it was killed.  Increase to two minutes.
=> [DM-26602] Relax elasticsearch-master liveness probe

deployments/logging/templates/logging-security-config.yaml
Backslashes in quoted strings need to be doubled.
=> [DM-26602] Fix escaping of proxy logging config

deployments/logging/templates/networkpolicy.yaml
See if this is the problem with Kibana being unable to talk to the
rest of the cluster.
=> [DM-26602] Allow other logging pods to connect to Kibana

deployments/logging/templates/networkpolicy.yaml, deployments/logging/values.yaml
The secrets and configuration maps were not being properly picked
up because they were indented by one too many levels.
=> [DM-26602] Fix indentation for fluentd-elasticsearch config

deployments/logging/values.yaml
For some reason, Kibana was previously not pointed at the correct
Elasticsearch hosts.  Fix that and disable SSL verification.
=> [DM-26602] Fix Kibana's Elasticsearch host configuration

deployments/logging/values.yaml
Otherwise it tries to use the GKE ingress, which (a) we don't want,
and (b) doesn't support ClusterIP.
=> [DM-26602] Use nginx ingress for Kibana

deployments/logging/values.yaml
There was a syntax error in the configuration snippet (missing
ending semicolon) that prevented it from being loaded).
=> [DM-26602] Fix syntax for proxy_set_header for Kibana

deployments/logging/values.yaml
Kibana was listening only to localhost, which makes it impossible
to access it via a service.
=> [DM-26602] Tell Kibana to listen to all addresses

deployments/logging/values.yaml
We also have to set rewriteBasePath to future-proof the behavior.
=> [DM-26602] Another Kibana base path fix

deployments/logging/values.yaml
See if this explains why permission is denied for all actions in
Kibana.
=> [DM-26602] Pass securitytenant header to Elasticsearch

deployments/logging/values.yaml
Trying to use anything other than admin seems to be a recipe for
frustration, so just force the role to admin at least for now.
=> [DM-26602] Set default Elasticsearch role to admin

deployments/logging/templates/logging-security-config.yaml, deployments/logging/values.yaml
This seems to be causing more confusion than it's worth.  Also be
explicit about the roles header to see if that's what's breaking
elasticsearch-client permissions.
=> [DM-26602] Disable multitenancy in Kibana

deployments/gafaelfawr/requirements.yaml, deployments/logging/templates/logging-security-config.yaml, deployments/logging/values.yaml
Do an end-to-end test of Kibana with OpenID Connect authentication.
We'll probably still use proxy authentication going forward, but I
want to test whether the OpenID Connect support in Gafaelfawr works
properly.
=> [DM-26602] Test Kibana with OpenID Connect

deployments/logging/values.yaml
Looks like we're getting an extra /logs parameter.  Try removing it
from the base redirect URL.
=> [DM-26602] Fix Kibana OpenID base redirect URL

deployments/logging/templates/logging-security-config.yaml
We're not setting scope to a valid format for the Elasticsearch
roles, so try testing without it.
=> [DM-26602] Remove roles key from Elasticsearch OpenID config

deployments/gafaelfawr/values.yaml, deployments/logging/templates/logging-security-config.yaml, deployments/logging/values.yaml, docs/ops/logging/index.rst, docs/ops/logging/openid-connect.rst
Switch back to proxy authentication for Kibana since it's easier
to use with roles, but add tested documentation for how to use
OpenID Connect should it ever be useful in the future.
Revert to the default Gafaelfawr deployment, since we don't need
the new endpoint for proxy authentication.  We'll pick it up later
with the next regular Gafaelfawr release.
=> [DM-26602] Restore proxy Kibana authentication, document OpenID

deployments/lsst-the-docs/patches/keeper-deployment.yaml
This is to make log correlation easier in Argo CD.
=> DM-27805: Reduce LTD replication to 1

deployments/vault-secrets-operator/requirements.yaml
This fixes ownership of secrets so that they're chained off of
vault secrets.
=> Bump vault-secrets-operator to 1.10.1

deployments/events/resources/kafka.yaml
There are crash loop back-offs restarting Kafka and Zookeeper pods; reducing the cluster size might help reset the cluster health.
=> DM-27995: Reduce Kafka and Zookeeper to single replica

deployments/argo-cd/patches/argocd-cm.yaml, deployments/ingress-nginx/Chart.yaml, deployments/ingress-nginx/README.md, deployments/ingress-nginx/values.yaml, deployments/logging/templates/kibana-networkpolicy.yaml, deployments/nginx-ingress/Chart.yaml, deployments/nginx-ingress/README.md, deployments/nginx-ingress/requirements.yaml, deployments/security/kustomization.yaml, deployments/security/resources/ingress-nginx.yaml, docs/conf.py, docs/ops/argo-cd/argocd-github-sso.rst, docs/ops/cert-manager/index.rst, docs/ops/events/cluster-config-overview.rst, docs/ops/gke/gke-cluster-setup.rst, docs/ops/gke/howto-connect-to-gke.rst, docs/ops/index.rst, docs/ops/ingress-nginx/index.rst, docs/ops/prometheus/grafana-github-sso.rst, docs/ops/security/index.rst
The nginx-ingress chart is no longer maintained in favor of an
ingress-nginx chart maintained by the same team as the ingress
code itself.  Switch Roundtable to the latest version of that
chart.  Switch the chart to Helm v3 in the process, since this is
required by the upstream chart.
=> [DM-27978] Switch from nginx-ingress to ingress-nginx

deployments/argo-cd/patches/argocd-cm.yaml, deployments/kube-prometheus-stack/Chart.yaml, deployments/kube-prometheus-stack/README.md, deployments/kube-prometheus-stack/templates/vault-secret.yaml, deployments/kube-prometheus-stack/values.yaml, deployments/roundtable/kustomization.yaml, deployments/roundtable/resources/kube-prometheus-stack.yaml, docs/conf.py, docs/ops/index.rst, docs/ops/kube-prometheus-stack/grafana-github-sso.rst, docs/ops/kube-prometheus-stack/index.rst, docs/ops/roundtable/index.rst
The older Prometheus chart has been deprecated and the new recommended
Helm chart is kube-prometheus-system.  Replace the old Prometheus
configuration with the new chart.  Since the data from the current
system is not currently that significant, this uninstalls the old
Prometheus install and creates a new one rather than trying to preserve
and move the persistent volumes.
Add a VaultSecret for the Grafana GitHub OAuth 2 secret, which was
previously using a manually-created secret.  (The relevant secret has
already been stored in Vault.)
=> [DM-27977] Replace prometheus with kube-prometheus-system

deployments/argo-cd/resources/argocd-metrics.yaml, deployments/argo-cd/resources/argocd-repo-server-metrics.yaml, deployments/argo-cd/resources/argocd-server-metrics.yaml, deployments/kube-prometheus-stack/values.yaml
Fix the labels so that Argo CD metrics are picked up and revert
the change to the namespace selector, which appears to not be
needed.
=> [DM-27977] Fix Argo CD ServiceMonitor annotations

renovate.json
Renovate seems to now be defaulting to 2 concurrent PRs, so bump
that to five to try to process more updates.  Remove the weekly
schedule for now to get through the backlog.
=> Remove weekly Renovate schedule, bump concurrency

deployments/cert-manager/Chart.yaml, deployments/cert-manager/requirements.yaml, deployments/gafaelfawr/Chart.yaml, deployments/gafaelfawr/requirements.yaml, deployments/logging/Chart.yaml, deployments/logging/requirements.yaml, deployments/strimzi/Chart.yaml, deployments/strimzi/requirements.yaml, deployments/vault-secrets-operator/Chart.yaml, deployments/vault-secrets-operator/requirements.yaml
I think this is the reason why some charts won't update in the
Argo CD dashboard.  Try using Helm 3 for everything, following a
change we already made on Phalanx.
=> Switch to Helm 3 for all wrapper charts

renovate.json
Rather than returning to a weekly schedule, which only gives
Renovate three runs to open its PRs, give it until 6am on Monday
morning to open its PRs.  Since it's only willing to open one or
two an hour, this ensures it can reach the PR limit of 5.
=> Update Renovate schedule

deployments/checkerboard/kustomization.yaml, deployments/neophile/Chart.yaml, deployments/ook/kustomization.yaml, deployments/safirdemo/kustomization.yaml, deployments/segwarides/kustomization.yaml
Install new versions of checkerboard, neophile, ook, safirdemo,
and segwarides to pick up refreshed dependencies.  The
segwarides Kustomize manifest now pins its Docker version to the
current release, so we don't need to do that in Roundtable.
=> [DM-28993] Bump service versions

deployments/lsst-the-docs/kustomization.yaml
Update LTD Keeper to 1.22.0 to support a longer TTL for presigned build upload URLs to S3.
=> DM-29879: Update LTD Keeper to 1.22.0

deployments/lsst-the-docs/kustomization.yaml
This update to LTD Dasher should resolve the TLS handshake issue that started October 1st.
=> DM-32026: Update LTD Dasher to 0.1.11

deployments/security/resources/ingress-nginx.yaml
When the Service for ingress-nginx-controller is created, it
populates spec/ipFamilies and spec/ipFamilyPolicy.  Tell Argo CD
to ignore those fields for determining whether the application is
out of date.
=> Ignore uninteresting ingress-nginx diffs

deployments/app-land/kustomization.yaml, deployments/app-land/resources/sqrbot.yaml, deployments/sqrbot/kustomization.yaml, deployments/sqrbot/resources/deployment.yaml, deployments/sqrbot/resources/vaultsecret.yaml
This deployment is fairly simple and is based entirely off manifests in roundtable, without referencing the https://github.com/lsst-sqre/sqrbot repo. The original secrets from the api.lsst.codes deployment are now in Vault under secret/k8s_operator/roundtable/sqrbot.
=> Create sqrbot (hubot) deployment

deployments/events/kustomization.yaml, deployments/events/patches/strimzi-registry-operator-deployment.yaml, deployments/events/resources/schemaregistry.yaml
Along with a new container build, this ticket-branch-based version also uses a newer Kubernetes API version in the CRDs.
=> Use DM-33317 v of strimzi-registry-operator

deployments/app-land/kustomization.yaml, deployments/events/kustomization.yaml, renovate.json
- Drop the sqrbot-jsick development app from running; leave the manifest so it'll be easy to spin back up when needed
- Have renovate ignore these testing apps to avoid confusion with what's running.
=> DM-33317: Spin down sqrbot-jsick app and have renovate ignore them

deployments/events/kustomization.yaml
Final deployment for DM-33317 to use the 0.4.0 release of strimzi-registry-operator
=> DM-33317: Deploy strimzi-registry-operator 0.4.0

deployments/events/patches/strimzi-registry-operator-deployment.yaml
The new env settings weren't merged into the right place in the
Deployment manifest
=> Fix strimzi-registry-operator patch

docs/ops/app-land/index.rst, docs/ops/argo-cd/argocd-github-sso.rst, docs/ops/argo-cd/argocd-rbac.rst, docs/ops/argo-cd/helm-repositories.rst, docs/ops/argo-cd/repositories.rst, docs/ops/argo-cd/upgrading.rst, docs/ops/ingress-nginx/index.rst, docs/ops/kube-prometheus-stack/grafana-github-sso.rst, docs/ops/kube-prometheus-stack/index.rst, docs/ops/roundtable/index.rst, docs/ops/security/index.rst
One of the CRDs is too long to sync normally and needs to be
manually synced with the Replace option set.  Document this.
=> Document kube-prometheus-stack CRD sync workaround

deployments/neophile/values.yaml
Use neophile to keep the pre-commit pins up to date.
=> Add templatekit and safir to neophile

deployments/sherlock-frontend/kustomization.yaml, deployments/sherlock-frontend/resources/secret.yaml
The secret is just part of the base manifests in the sherlock-frontend
repo.  Since we're just using it in the one place, it doesn't matter
much where it is.
=> [DM-34317] Sherlock 0.0.15

deployments/vault/values.yaml
Let the version of Vault update with the chart, since it's not
restarted automatically anyway and we can choose when to restart
it.
=> Unpin the Vault image version

deployments/neophile/values.yaml
Kafka requires Python 3.9 for now, which neophile doesn't cope
well with.  Disable neophile updates for those for the time being.
=> Ignore Kafka packages for neophile

deployments/rubintv/kustomization.yaml
This uses an authenticated bucket user again for Rubin TV.
=> DM-36727: Deploy rubin-tv development image

deployments/rubintv/kustomization.yaml
This deploys Rubin TV from https://github.com/lsst-sqre/rubin-tv/pull/117
=> DM-36870: Deploy rubin TV from dev branch

deployments/app-land/kustomization.yaml, deployments/app-land/resources/rubintv-dev.yaml, deployments/rubintv-dev/README.md, deployments/rubintv-dev/kustomization.yaml, deployments/rubintv-dev/patches/deployment.yaml, deployments/rubintv-dev/resources/ingress.yaml, deployments/rubintv-dev/resources/secret.yaml
This is a dev instance of Rubin TV. It's a separate app from the production instance, but shares the same secrets and configuration from prod; it simply tracks the "develop" branch.
It's deployed to a separate namespace, rubintv-dev, and hosted on the /rubintv-dev/ path with its own ingress.
=> DM-37164: Add rubintv-dev application

deployments/rubintv-dev/resources/ingress.yaml
rubintv-dev's ingress using the networking.k8s.io/v1 spec didn't work, so I'm trying it with the v1beta1 schema that other ingresses on Roundtable are using.
=> DM-37164: Switch rubintv-dev ingress to v1beta1 schema

deployments/1password-connect/Chart.yaml, deployments/1password-connect/README.md, deployments/1password-connect/templates/vault-secrets.yaml, deployments/1password-connect/values.yaml, deployments/app-land/kustomization.yaml, deployments/app-land/resources/1password-connect-ns.yaml, deployments/app-land/resources/1password-connect.yaml, deployments/app-land/resources/roundtable-ingress.yaml, docs/conf.py, docs/ops/1password-connect/index.rst, docs/ops/events/cluster-config-overview.rst, docs/ops/index.rst
We will use this server to retrieve RSP secrets from the relevant 1Password vault when bootstrapping a new Phalanx environment, or checking the secrets in an existing one.
=> DM-37721: Add 1Password Connect server

deployments/argo-cd/kustomization.yaml
We removed kube-prometheus-stack and all of these resources, but missed removing the pointers to them in kustomization.yaml.
=> Remove Argo CD metrics pointers

deployments/neophile/values.yaml
cachemachine, moneypenny, and nublado2 were only used with the older version of Nublado. Now that we're getting ready to deploy the new release everywhere, stop trying to update them with neophile.
=> Remove Nublado v2 services from neophile

deployments/neophile/Chart.yaml
The new version uses Python 3.11 instead of 3.10.
=> Bump version of neophile

deployments/argo-cd/patches/argocd-server-deployment.yaml
--insecure should now be --insecure=true, and upstream uses /usr/local/bin/argocd-server.  Drop --staticassets since upstream doesn't use that flag.
=> Hopefully fix Argo CD configuration

deployments/argo-cd/patches/argocd-server-deployment.yaml
Apparently the container is run in such a way that forces the command, so command should contain only the flags.
=> Remove the path to argocd-server

deployments/vault-secrets-operator/values.yaml
Don't create a secret for the vault-secrets-operator service account. This shouldn't be necessary and it conflicts with our secret with the Vault credentials.
=> Do not create secret for vault-secrets-operator

renovate.json
matchPaths appears to be deprecated. Switch to matchFileNames with wildcards.
=> Update Renovate configuration syntax

renovate.json
This reverts commit 5c29fbd3bb015f7f0f406bf0855336b23c89c124. Apparently Renovate is now back to running an older version?  Anyway, this produces an error and the old syntax now doesn't.
=> Revert "Update Renovate configuration syntax"

.github/workflows/docs.yaml
The docuemntation link check is failing due to the very old version of Sphinx not understanding 308 redirects. We're going to be turning off this cluster, so just stop running the link check so that tests can pass.
=> Disable the documentation link check

deployments/templatebot/kustomization.yaml
This development version of lsst-templatebot-aide provides
pre-validation of author_id before creating a github repo.
=> DM-42593: Update templatebot-aide

deployments/lsst-the-docs/patches/keeper-deployment.yaml, deployments/sqrbot-jr/patches/deployment.yaml
In preparation for rotating the Kubernetes cluster CA, turn down the front-ends for LTD and sqrbot-jr to drain in-flight traffic during the migration.
=> DM-45678: Turn off LTD and sqrbot-jr front-ends for Kubernetes cluster rotation

deployments/events/resources/demo-user.yaml, deployments/events/resources/kafka.yaml, deployments/events/resources/ltdevents-topics.yaml, deployments/events/resources/ltdevents-user.yaml, deployments/events/resources/ook-topics.yaml, deployments/events/resources/ook-user.yaml, deployments/events/resources/schemaregistry-user.yaml, deployments/events/resources/schemaregistry.yaml, deployments/events/resources/schemas-topic.yaml, deployments/events/resources/sqrbot-jr-topics.yaml, deployments/events/resources/sqrbot-jr-user.yaml, deployments/events/resources/sqrbot-jsick-topics.yaml, deployments/events/resources/sqrbot-jsick-user.yaml, deployments/events/resources/templatebot-jsick-topics.yaml, deployments/events/resources/templatebot-jsick-user.yaml, deployments/events/resources/templatebot-topics.yaml, deployments/events/resources/templatebot-user.yaml, deployments/strimzi/Chart.yaml, deployments/strimzi/values.yaml
This PR is a multi-version upgrade attempt to bring Strimzi to a version compatible with Kubernetes 1.27.11. 
We run the [Strimzi API conversion tool](https://strimzi.io/docs/operators/0.24.0/deploying#proc-upgrade-cli-tool-files-str) to make Strimzi resources compatible with `v1beta2` .
[Strimzi 0.29.0](https://strimzi.io/downloads/) is the minimal version compatible with Kubernetes 1.27.11.
We avoid upgrading Strimzi to a more recent version to minimize changes, for example the introduction of the Unidirectional Topic Operator and Kraft.
=> [DM-46295] Upgrade Strimzi in the Roundtable cluster
